export var WEBHOOK_POSTGRES_CHANGES_TYPE;
(function (WEBHOOK_POSTGRES_CHANGES_TYPE) {
    WEBHOOK_POSTGRES_CHANGES_TYPE["INSERT"] = "INSERT";
    WEBHOOK_POSTGRES_CHANGES_TYPE["UPDATE"] = "UPDATE";
    WEBHOOK_POSTGRES_CHANGES_TYPE["DELETE"] = "DELETE";
})(WEBHOOK_POSTGRES_CHANGES_TYPE || (WEBHOOK_POSTGRES_CHANGES_TYPE = {}));
